<a href="https://colab.research.google.com/github/vaishnavi-eklaspur/EDS-ASSIGNMENT/blob/main/ASSIGNMENT3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data1=np.loadtxt("/content/testmarks1 - testmarks1 (1).csv",skiprows=1, delimiter=",", dtype=float)
data2=np.loadtxt("/content/testmarks2 - testmarks2.csv",skiprows=1, delimiter=",", dtype=float)
print("SET1 IS:",data1)
print("SET2 IS:",data2)

#addition
A=np.add(data1,data2)
print("ADDITION OF TWO MATRIX IS:",A,"\n")

#subtraction
B=np.subtract(data1,data2)
print("SUBTRACTION OF TWO MATRIX IS:",B,"\n")

#multiplication
C=np.multiply(data1,data2)
print("MULTIPLICATION OF TWO MATRIX IS:",C,"\n")

#HORIZONTAL STACK
print("HORIZONTAL STACK OF DATA1 IS:\n",np.hstack(data1))
print("HORIZONTAL STACK OF DATA2 IS:\n",np.hstack(data2))

#VERTICAL STACK
print("VERTICAL STACK OF DATA1 IS:\n",np.vstack(data1))
print("VERTICAL STACK OF DATA2 IS:\n",np.vstack(data2))

#MAXIMUM
g=np.max(A,axis=0)
h=int(g[0]/2)
print("THE STUDENTs GOT MAXIMUM MARKS IN:\n",h)

#Minimum
f=np.min(A,axis=0)
i=int(f[0]/2)
print("THE STUDENTs GOT MAXIMUM MARKS IN:\n",f)

#sorting
print("sorting data1\n",np.sort(data1),"\n")
print("sorting data2\n",np.sort(data2),"\n")



SET1 IS: [[801.    43.05  27.79  28.7   27.79]
 [802.    43.47  28.52  28.98  27.89]
 [803.    42.24  28.16  28.16  25.63]
 [804.    39.24  26.16  26.16  26.16]
 [805.    40.9   26.03  27.27  25.65]
 [806.    39.47  26.31  26.31  25.21]
 [807.    41.68  25.63  27.79  25.46]
 [808.    42.19  27.61  28.13  26.21]
 [809.    44.75  28.35  29.83  28.21]
 [810.    46.95  28.88  31.3   28.53]]
SET2 IS: [[801.    28.48  34.18  30.56  22.23]
 [802.    28.1   33.72  30.68  22.82]
 [803.    26.16  31.39  28.2   22.53]
 [804.    26.16  31.39  28.78  20.93]
 [805.    26.1   31.32  28.22  20.82]
 [806.    25.45  30.54  27.73  21.05]
 [807.    26.16  31.39  28.01  20.51]
 [808.    27.44  32.93  28.83  22.08]
 [809.    28.63  34.35  31.03  22.68]
 [810.    30.35  36.42  31.38  23.1 ]]
ADDITION OF TWO MATRIX IS: [[1602.     71.53   61.97   59.26   50.02]
 [1604.     71.57   62.24   59.66   50.71]
 [1606.     68.4    59.55   56.36   48.16]
 [1608.     65.4    57.55   54.94   47.09]
 [1610.     67.     5